### ISSUE TITLE
Feature: User Entity, Controller

### ISSUE THREAD

**Issue by hyeonahhh** [1J3P/FarmFarm#15]
## 💡 Issue

User 엔티티 관련 이슈(entity, controller 작성)

## ✅ To-do List

- [ ] kakao developer 설정
- [ ] user entity 수정
- [ ] user controller 작성
- [ ] application.properties 수정
