### ISSUE TITLE
feat: jsp 수정

### ISSUE THREAD

**Issue by khskys0805** [1J3P/FarmFarm#166]
## 💡 Issue

마이페이지 이미지 깨지는거 수정, 농장 jsp 분기 처리, 상품 없을 때 문구 띄우기
## ✅ To-do List

- [ ] 마이페이지 이미지 깨지는거 수정
- [ ] 농장 jsp 분기 처리
- [ ] 상품 없을 때 문구 띄우기
