### ISSUE TITLE
feature: Product 검색, Product 리스트 정렬

### ISSUE THREAD

**Issue by harinLeeee** [1J3P/FarmFarm#37]
## 💡 Issue

Product 검색 및 Product 리스트 정렬

## ✅ To-do List

- [x] 상품 검색
- [x] 상품 인기순 정렬
- [x] 상품 신상품순 정렬
- [x] 상품 낮은 가격순 정렬
- [x] 상품 높은 가격순 정렬
- [x] ProductEntity rating(double) 필드 추가
- [x] ProductEntity sales(int) 필드 추가
- [x] ReviewEntity productStar, farmStar(double) 필드 추가
- [x] ProductEntity is_auction(Boolean) 필드 타입 변경
