### ISSUE TITLE
fix: 상품 수정

### ISSUE THREAD

**Issue by harinLeeee** [1J3P/FarmFarm#85]
## 💡 Issue

전체적인 product 수정 사항을 반영 할 예정

## ✅ To-do List

- [x] 상품 등록 시 경매일 경우 농장이 경매 농장인지 확인 필요
- [x] 결제 완료 및 취소 시 product quantity, sales 조정
- [x] 상품 상세 조회 누르고 일반 상품과 경매 상품 구분하여 view로 보내기
- [x] product entity auction_quantity 추가
- [x] 경매 상품 리스트 보기 추가
